[package]
name = "allfeat-primitives"
version = "1.0.0"
authors = ["Allfeat labs. <tech@allfeat.com>"]
description = "Allfeat node/runtime low-level primitives."
edition = "2021"
license = "Apache-2.0"
homepage = "https://allfeat.network"
repository = "https://github.com/Allfeat/Allfeat"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
sp-core = { version = "21.0.0", default-features = false, git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v1.0.0" }
sp-runtime = { version = "24.0.0", default-features = false, git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v1.0.0" }
fp-account = { version = "1.0.0-dev", git = "https://github.com/paritytech/frontier.git", branch = "polkadot-v1.0.0", default-features = false, features = ["serde"] }

[features]
default = ["std"]
std = [
	"sp-core/std",
	"sp-runtime/std",
	"fp-account/std"
]
