# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

name: 'Build and Test'

steps:
- script: sudo apt install -y git clang curl libssl-dev llvm libudev-dev
  displayName: 'Set-up'

- script: |
    curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
    source ~/.cargo/env
    rustup default stable
    rustup update nightly
    rustup update stable
    rustup target add wasm32-unknown-unknown --toolchain nightly
  displayName: 'Install Rustup'

- script: SKIP_WASM_BUILD=1 cargo build --release
  displayName: 'Build'

- script: SKIP_WASM_BUILD=1 cargo test --release
  displayName: 'Testing'
