[workspace]
resolver = "2"
members = [
	"node",
	"runtime/*",
	"primitives",
	"pallets/*",
	"midds/stakeholder",
	"midds/song",
	"support",
	"support/genres-registry",
]

[workspace.package]
authors = ["Allfeat labs. <hello@allfeat.com>"]
edition = "2021"
homepage = "https://allfeat.network"
license = "GPL-3.0"
repository = "https://github.com/allfeat/allfeat"
version = "1.0.0-dev"

[workspace.dependencies]
# Dependencies are split into 2 groups: wasm and client.
# - "wasm" dependencies requires to be no_std compatible, which often requires
#   `default-features = false`. When used in a client-side crate the "std" feature should be enabled
#   there if it exists.
# - "client" dependencies are only used in the client, and thus don't need to be no_std compatible.

# Allfeat (wasm)
allfeat-support = { version = "1.0.0-dev", default-features = false, path = "./support" }
allfeat-primitives = { version = "1.0.0", default-features = false, path = "./primitives" }
pallet-midds = { version = "1.0.0-dev", default-features = false, path = "./pallets/midds/" }
genres-registry = { package = "genres-registry", version = "1.0.0-dev", default-features = false, path = "./support/genres-registry" }
# midds-artist = { version = "1.0.0-dev", default-features = false, path = "./midds/artist" }
midds-stakeholder = { version = "1.0.0-dev", default-features = false, path = "./midds/stakeholder" }
midds-song = { version = "1.0.0-dev", default-features = false, path = "./midds/song" }

polkadot-sdk = { version = "0.7.0", default-features = false, git = "https://github.com/paritytech/polkadot-sdk", tag = "polkadot-stable2409-2" }

# Substrate (wasm)
parity-scale-codec = { version = "3.6.12", default-features = false, features = [
	"derive",
] }
scale-info = { version = "2.11.3", default-features = false, features = [
	"derive",
] }
static_assertions = "1.1.0"
log = { version = "0.4.22", default-features = false }
hex-literal = "0.4.1"
smallvec = "1.13.2"
array-bytes = "6.2"

pallet-validator-set = { package = "substrate-validator-set", version = "1.1.0", default-features = false, git = "https://github.com/Allfeat/substrate-validator-set.git", tag = "polkadot-stable2409-2" }

# Other (wasm)
num_enum = { version = "0.7.3", default-features = false }
enumflags2 = { version = "0.7.10" }

# Allfeat (client)
shared-runtime = { version = "1.0.0-dev", path = "./runtime/shared", default-features = false }
melodie-runtime = { version = "1.0.0-dev", path = "./runtime/melodie" }

# Other (client)
clap = { version = "4.5.13", features = ["derive"] }
serde = { version = "1.0.204", features = ["derive"] }
jsonrpsee = { version = "0.23.2", features = ["server", "macros"] }
serde_json = { version = "1.0.122", default-features = false }
futures = "0.3.30"
rand = "0.8.5"
tempfile = "3.11.0"
sha3 = { version = "0.10.8", default-features = false }
bip32 = { version = "0.5.2", default-features = false, features = ["bip39"] }

# make sure dev builds with backtrace do
# not slow us down
[profile.dev.package.backtrace]
inherits = "release"

[profile.ci]
debug = false
incremental = false
inherits = "dev"
opt-level = "z"

[profile.production]
codegen-units = 1
incremental = false
inherits = "release"
lto = true

[profile.release]
# Allfeat runtime requires unwinding.
opt-level = 3
panic = "unwind"
