apiVersion: v1
kind: Service
metadata:
  name: {{ include "allfeat-node.fullname" . }}
  labels:
    {{- include "allfeat-node.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.rpcPort }}
      targetPort: rpc
      protocol: TCP
      name: rpc
    {{- if .Values.metrics.enabled }}
    - port: {{ .Values.service.metricsPort }}
      targetPort: metrics
      protocol: TCP
      name: metrics
    {{- end }}
  selector:
    {{- include "allfeat-node.selectorLabels" . | nindent 4 }}

---
{{- if .Values.p2pService.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "allfeat-node.fullname" . }}-p2p
  labels:
    {{- include "allfeat-node.labels" . | nindent 4 }}
    app.kubernetes.io/component: p2p
  {{- with .Values.p2pService.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.p2pService.type }}
  ports:
    - port: {{ .Values.p2pService.port }}
      targetPort: p2p
      protocol: TCP
      name: p2p
      {{- if and (eq .Values.p2pService.type "NodePort") .Values.p2pService.nodePort }}
      nodePort: {{ .Values.p2pService.nodePort }}
      {{- end }}
  selector:
    {{- include "allfeat-node.selectorLabels" . | nindent 4 }}
{{- end }}
