// This file is part of Allfeat.

// Copyright (C) 2022-2025 Allfeat.
// SPDX-License-Identifier: GPL-3.0-or-later

// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.

// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
// GNU General Public License for more details.

// You should have received a copy of the GNU General Public License
// along with this program. If not, see <https://www.gnu.org/licenses/>.

//! Autogenerated weights for `pallet_balances`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 51.0.0
//! DATE: 2025-11-02, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `ip-172-31-46-127.eu-west-3.compute.internal`, CPU: `Intel(R) Xeon(R) Platinum 8375C CPU @ 2.90GHz`
//! WASM-EXECUTION: `Compiled`, CHAIN: `None`, DB CACHE: `1024`

// Executed Command:
// frame-omni-bencher
// v1
// benchmark
// pallet
// --runtime
// ./target/release/wbuild/allfeat-runtime/allfeat_runtime.compact.compressed.wasm
// --genesis-builder-preset=staging
// --pallet=pallet_balances
// --extrinsic=*
// --output=./runtime/mainnet/src/weights/balances.rs
// --header=./HEADER
// --template=./.maintain/runtimes-weight-template.hbs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]
#![allow(dead_code)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use core::marker::PhantomData;
use pallet_balances::WeightInfo;

pub struct AllfeatWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for AllfeatWeight<T> {
        /// Storage: `System::Account` (r:1 w:1)
        /// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
        fn transfer_allow_death() -> Weight {
                // Proof Size summary in bytes:
                //  Measured:  `0`
                //  Estimated: `3593`
                // Minimum execution time: 55_840_000 picoseconds.
                Weight::from_parts(57_132_000, 3593)
                        .saturating_add(T::DbWeight::get().reads(1_u64))
                        .saturating_add(T::DbWeight::get().writes(1_u64))
        }
        /// Storage: `System::Account` (r:1 w:1)
        /// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
        fn transfer_keep_alive() -> Weight {
                // Proof Size summary in bytes:
                //  Measured:  `0`
                //  Estimated: `3593`
                // Minimum execution time: 43_854_000 picoseconds.
                Weight::from_parts(44_617_000, 3593)
                        .saturating_add(T::DbWeight::get().reads(1_u64))
                        .saturating_add(T::DbWeight::get().writes(1_u64))
        }
        /// Storage: `System::Account` (r:1 w:1)
        /// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
        fn force_set_balance_creating() -> Weight {
                // Proof Size summary in bytes:
                //  Measured:  `0`
                //  Estimated: `3593`
                // Minimum execution time: 22_068_000 picoseconds.
                Weight::from_parts(22_409_000, 3593)
                        .saturating_add(T::DbWeight::get().reads(1_u64))
                        .saturating_add(T::DbWeight::get().writes(1_u64))
        }
        /// Storage: `System::Account` (r:1 w:1)
        /// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
        fn force_set_balance_killing() -> Weight {
                // Proof Size summary in bytes:
                //  Measured:  `103`
                //  Estimated: `3593`
                // Minimum execution time: 22_760_000 picoseconds.
                Weight::from_parts(23_222_000, 3593)
                        .saturating_add(T::DbWeight::get().reads(1_u64))
                        .saturating_add(T::DbWeight::get().writes(1_u64))
        }
        /// Storage: `System::Account` (r:2 w:2)
        /// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
        fn force_transfer() -> Weight {
                // Proof Size summary in bytes:
                //  Measured:  `103`
                //  Estimated: `6196`
                // Minimum execution time: 57_644_000 picoseconds.
                Weight::from_parts(58_727_000, 6196)
                        .saturating_add(T::DbWeight::get().reads(2_u64))
                        .saturating_add(T::DbWeight::get().writes(2_u64))
        }
        /// Storage: `System::Account` (r:1 w:1)
        /// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
        fn transfer_all() -> Weight {
                // Proof Size summary in bytes:
                //  Measured:  `0`
                //  Estimated: `3593`
                // Minimum execution time: 53_852_000 picoseconds.
                Weight::from_parts(55_524_000, 3593)
                        .saturating_add(T::DbWeight::get().reads(1_u64))
                        .saturating_add(T::DbWeight::get().writes(1_u64))
        }
        /// Storage: `System::Account` (r:1 w:1)
        /// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
        fn force_unreserve() -> Weight {
                // Proof Size summary in bytes:
                //  Measured:  `103`
                //  Estimated: `3593`
                // Minimum execution time: 18_795_000 picoseconds.
                Weight::from_parts(19_076_000, 3593)
                        .saturating_add(T::DbWeight::get().reads(1_u64))
                        .saturating_add(T::DbWeight::get().writes(1_u64))
        }
        /// Storage: `System::Account` (r:999 w:999)
        /// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
        /// The range of component `u` is `[1, 1000]`.
        fn upgrade_accounts(u: u32, ) -> Weight {
                // Proof Size summary in bytes:
                //  Measured:  `0 + u * (136 ±0)`
                //  Estimated: `990 + u * (2603 ±0)`
                // Minimum execution time: 18_457_000 picoseconds.
                Weight::from_parts(18_840_000, 990)
                        // Standard Error: 6_954
                        .saturating_add(Weight::from_parts(15_771_471, 0).saturating_mul(u.into()))
                        .saturating_add(T::DbWeight::get().reads((1_u64).saturating_mul(u.into())))
                        .saturating_add(T::DbWeight::get().writes((1_u64).saturating_mul(u.into())))
                        .saturating_add(Weight::from_parts(0, 2603).saturating_mul(u.into()))
        }
        fn force_adjust_total_issuance() -> Weight {
                // Proof Size summary in bytes:
                //  Measured:  `0`
                //  Estimated: `0`
                // Minimum execution time: 6_279_000 picoseconds.
                Weight::from_parts(6_508_000, 0)
        }
        fn burn_allow_death() -> Weight {
                // Proof Size summary in bytes:
                //  Measured:  `0`
                //  Estimated: `0`
                // Minimum execution time: 35_766_000 picoseconds.
                Weight::from_parts(36_681_000, 0)
        }
        fn burn_keep_alive() -> Weight {
                // Proof Size summary in bytes:
                //  Measured:  `0`
                //  Estimated: `0`
                // Minimum execution time: 23_623_000 picoseconds.
                Weight::from_parts(24_271_000, 0)
        }
}
