// This file is part of Allfeat.

// Copyright (C) 2022-2025 Allfeat.
// SPDX-License-Identifier: GPL-3.0-or-later

// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.

// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
// GNU General Public License for more details.

// You should have received a copy of the GNU General Public License
// along with this program. If not, see <https://www.gnu.org/licenses/>.

//! Autogenerated weights for `pallet_im_online`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 51.0.0
//! DATE: 2025-11-02, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `ip-172-31-46-127.eu-west-3.compute.internal`, CPU: `Intel(R) Xeon(R) Platinum 8375C CPU @ 2.90GHz`
//! WASM-EXECUTION: `Compiled`, CHAIN: `None`, DB CACHE: `1024`

// Executed Command:
// frame-omni-bencher
// v1
// benchmark
// pallet
// --runtime
// ./target/release/wbuild/allfeat-runtime/allfeat_runtime.compact.compressed.wasm
// --genesis-builder-preset=staging
// --pallet=pallet_im_online
// --extrinsic=*
// --output=./runtime/mainnet/src/weights/im_online.rs
// --header=./HEADER
// --template=./.maintain/runtimes-weight-template.hbs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]
#![allow(dead_code)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use core::marker::PhantomData;
use pallet_im_online::WeightInfo;

pub struct AllfeatWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for AllfeatWeight<T> {
        /// Storage: `Session::Validators` (r:1 w:0)
        /// Proof: `Session::Validators` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
        /// Storage: `Session::CurrentIndex` (r:1 w:0)
        /// Proof: `Session::CurrentIndex` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
        /// Storage: `ImOnline::Keys` (r:1 w:0)
        /// Proof: `ImOnline::Keys` (`max_values`: Some(1), `max_size`: Some(320002), added: 320497, mode: `MaxEncodedLen`)
        /// Storage: `ImOnline::ReceivedHeartbeats` (r:1 w:1)
        /// Proof: `ImOnline::ReceivedHeartbeats` (`max_values`: None, `max_size`: Some(25), added: 2500, mode: `MaxEncodedLen`)
        /// The range of component `k` is `[1, 10000]`.
        fn validate_unsigned_and_then_heartbeat(k: u32, ) -> Weight {
                // Proof Size summary in bytes:
                //  Measured:  `83 + k * (32 ±0)`
                //  Estimated: `321487 + k * (32 ±0)`
                // Minimum execution time: 60_013_000 picoseconds.
                Weight::from_parts(47_240_571, 321487)
                        // Standard Error: 515
                        .saturating_add(Weight::from_parts(59_162, 0).saturating_mul(k.into()))
                        .saturating_add(T::DbWeight::get().reads(4_u64))
                        .saturating_add(T::DbWeight::get().writes(1_u64))
                        .saturating_add(Weight::from_parts(0, 32).saturating_mul(k.into()))
        }
}
