replicaCount: 1

image:
  repository: allfeat/allfeat-node
  tag: "v1.0.0"
  pullPolicy: IfNotPresent

node:
  devMode: false
  chain: "mainnet"
  name: "prod-allfeat-node"
  network:
    port: 30333
    publicAddr: "/ip4/YOUR_PUBLIC_IP/tcp/30333"
    bootnodes: "/ip4/bootnode1.example.com/tcp/30333/p2p/12D3KooW...,/ip4/bootnode2.example.com/tcp/30333/p2p/12D3KooW..."

persistence:
  enabled: true
  storageClass: "fast-ssd"
  size: 500Gi

resources:
  requests:
    cpu: 2000m
    memory: 4Gi
  limits:
    cpu: 4000m
    memory: 8Gi

p2pService:
  enabled: true
  type: LoadBalancer

rpc:
  external: true
  methods: "safe"

metrics:
  enabled: true
  external: false

serviceMonitor:
  enabled: true

networkPolicy:
  enabled: true

podDisruptionBudget:
  enabled: true
  minAvailable: 1

livenessProbe:
  enabled: true
  initialDelaySeconds: 60
  periodSeconds: 30

readinessProbe:
  enabled: true
  initialDelaySeconds: 30
  periodSeconds: 10
