[package]
authors.workspace = true
description = "Shared stuffs for Allfeat runtimes."
edition.workspace = true
name = "shared-runtime"
version.workspace = true

[dependencies]
enumflags2 = { workspace = true }
parity-scale-codec = { workspace = true, features = ["derive", "max-encoded-len"] }
scale-info = { workspace = true, features = ["derive"] }
smallvec = { workspace = true }

sp-core = { workspace = true }
sp-runtime = { workspace = true }
sp-std = { workspace = true }
frame-system = { workspace = true }
frame-support = { workspace = true }
frame-metadata-hash-extension = { workspace = true }

pallet-identity = { workspace = true }
pallet-artists = { workspace = true }
pallet-election-provider-multi-phase = { workspace = true }
pallet-im-online = { workspace = true }
pallet-multisig = { workspace = true }
pallet-nomination-pools = { workspace = true }
pallet-preimage = { workspace = true }
pallet-proxy = { workspace = true }
pallet-session = { workspace = true }
pallet-scheduler = { workspace = true }
pallet-balances = { workspace = true, features = ["insecure_zero_ed"] }
pallet-sudo = { workspace = true }
pallet-timestamp = { workspace = true }
pallet-utility = { workspace = true }
pallet-transaction-payment = { workspace = true }
pallet-evm = { workspace = true }
pallet-ethereum = { workspace = true }

fp-rpc = { workspace = true }

allfeat-primitives = { workspace = true }

[features]
default = ["std"]
std = [
    "frame-system/std",
    "frame-support/std",
    "pallet-identity/std",
    "scale-info/std",
    "enumflags2/std",
    "sp-std/std",
    "sp-core/std",
    "sp-runtime/std",
    "allfeat-primitives/std",
    "parity-scale-codec/std",
    "pallet-artists/std",
    "pallet-transaction-payment/std",
    "pallet-election-provider-multi-phase/std",
    "pallet-im-online/std",
    "pallet-multisig/std",
    "pallet-nomination-pools/std",
    "pallet-preimage/std",
    "pallet-proxy/std",
    "pallet-session/std",
    "pallet-scheduler/std",
    "pallet-balances/std",
    "pallet-sudo/std",
    "pallet-timestamp/std",
    "pallet-utility/std",
    "pallet-evm/std",
    "pallet-ethereum/std",
    "frame-metadata-hash-extension/std",
    "fp-rpc/std"
]
runtime-benchmarks = [
    "pallet-identity/runtime-benchmarks",
    "frame-support/runtime-benchmarks",
    "frame-system/runtime-benchmarks",
    "pallet-artists/runtime-benchmarks",
    "pallet-balances/runtime-benchmarks",
    "pallet-election-provider-multi-phase/runtime-benchmarks",
    "pallet-evm/runtime-benchmarks",
    "pallet-im-online/runtime-benchmarks",
    "pallet-multisig/runtime-benchmarks",
    "pallet-nomination-pools/runtime-benchmarks",
    "pallet-preimage/runtime-benchmarks",
    "pallet-proxy/runtime-benchmarks",
    "pallet-scheduler/runtime-benchmarks",
    "pallet-sudo/runtime-benchmarks",
    "pallet-timestamp/runtime-benchmarks",
    "pallet-utility/runtime-benchmarks",
    "pallet-ethereum/runtime-benchmarks",
    "sp-runtime/runtime-benchmarks",
]
test = []