[package]
name = "shared-runtime"
version = "1.0.0-dev"
edition = "2021"
description = "Shared stuff used in runtimes."
authors.workspace = true

[dependencies]
enumflags2 = { workspace = true }
parity-scale-codec = { workspace = true, features = ["derive", "max-encoded-len"] }
scale-info = { workspace = true, features = ["derive"] }
smallvec = { workspace = true }

sp-core = { workspace = true }
sp-runtime = { workspace = true }
sp-std = { workspace = true }
frame-system = { workspace = true }
frame-support = { workspace = true }

pallet-identity = { workspace = true }
pallet-artists = { workspace = true }
pallet-authorship = { workspace = true }
pallet-bags-list = { workspace = true }
pallet-election-provider-multi-phase = { workspace = true }
pallet-im-online = { workspace = true }
pallet-multisig = { workspace = true }
pallet-nomination-pools = { workspace = true }
pallet-preimage = { workspace = true }
pallet-proxy = { workspace = true }
pallet-session = { workspace = true }
pallet-staking = { workspace = true }
pallet-scheduler = { workspace = true }
pallet-balances = { workspace = true, features = ["insecure_zero_ed"] }
pallet-sudo = { workspace = true }
pallet-timestamp = { workspace = true }
pallet-utility = { workspace = true }
pallet-transaction-payment = { workspace = true }
pallet-evm = { workspace = true }

allfeat-primitives = { workspace = true }

[features]
default = ["std"]
std = [
    "frame-system/std",
    "frame-support/std",
    "pallet-identity/std",
    "scale-info/std",
    "enumflags2/std",
    "sp-std/std",
    "sp-core/std",
    "sp-runtime/std",
    "allfeat-primitives/std",
    "parity-scale-codec/std",
    "pallet-artists/std",
    "pallet-transaction-payment/std",
    "pallet-bags-list/std",
    "pallet-election-provider-multi-phase/std",
    "pallet-im-online/std",
    "pallet-multisig/std",
    "pallet-nomination-pools/std",
    "pallet-preimage/std",
    "pallet-proxy/std",
    "pallet-session/std",
    "pallet-staking/std",
    "pallet-scheduler/std",
    "pallet-balances/std",
    "pallet-sudo/std",
    "pallet-timestamp/std",
    "pallet-utility/std",
    "pallet-evm/std",
    "pallet-authorship/std",
]
test = []