// This file is part of Allfeat.

// Copyright (C) 2022-2025 Allfeat.
// SPDX-License-Identifier: GPL-3.0-or-later

// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.

// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
// GNU General Public License for more details.

// You should have received a copy of the GNU General Public License
// along with this program. If not, see <https://www.gnu.org/licenses/>.

//! Autogenerated weights for pallet_midds_party_identifiers
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 32.0.0
//! DATE: 2025-06-11, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `melodie-node-weights`, CPU: `<UNKNOWN>`
//! EXECUTION: , WASM-EXECUTION: Compiled, CHAIN: None, DB CACHE: 1024

// Executed Command:
// frame-omni-bencher
// v1
// benchmark
// pallet
// --runtime
// ./target/release/wbuild/melodie-runtime/melodie_runtime.compact.compressed.wasm
// --genesis-builder-preset=development
// --pallet=pallet_midds_party_identifiers
// --extrinsic=*
// --output=./runtime/shared/src/weights/midds_party_identifiers.rs
// --header=./HEADER
// --template=./.maintain/frame-weight-template.hbs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use core::marker::PhantomData;

/// Weight functions needed for pallet_midds_party_identifiers.
pub trait WeightInfo {
	fn register(x: u32, ) -> Weight;
	fn unregister(x: u32, ) -> Weight;
}

/// Weights for pallet_midds_party_identifiers using the Allfeat node and recommended hardware.
pub struct AllfeatWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> pallet_midds::WeightInfo for AllfeatWeight<T> {
	/// Storage: `Timestamp::Now` (r:1 w:0)
	/// Proof: `Timestamp::Now` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `PartyIdentifiers::NextId` (r:1 w:1)
	/// Proof: `PartyIdentifiers::NextId` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `PartyIdentifiers::HashIndex` (r:1 w:1)
	/// Proof: `PartyIdentifiers::HashIndex` (`max_values`: None, `max_size`: Some(56), added: 2531, mode: `MaxEncodedLen`)
	/// Storage: `Balances::Holds` (r:1 w:1)
	/// Proof: `Balances::Holds` (`max_values`: None, `max_size`: Some(229), added: 2704, mode: `MaxEncodedLen`)
	/// Storage: `PartyIdentifiers::MiddsDb` (r:0 w:1)
	/// Proof: `PartyIdentifiers::MiddsDb` (`max_values`: None, `max_size`: Some(1911), added: 4386, mode: `MaxEncodedLen`)
	/// The range of component `x` is `[14, 1847]`.
	fn register(x: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `79`
		//  Estimated: `3694`
		// Minimum execution time: 87_601_000 picoseconds.
		Weight::from_parts(97_123_977, 3694)
			// Standard Error: 337
			.saturating_add(Weight::from_parts(1_676, 0).saturating_mul(x.into()))
			.saturating_add(T::DbWeight::get().reads(4_u64))
			.saturating_add(T::DbWeight::get().writes(4_u64))
	}
	/// Storage: `PartyIdentifiers::MiddsDb` (r:1 w:1)
	/// Proof: `PartyIdentifiers::MiddsDb` (`max_values`: None, `max_size`: Some(1911), added: 4386, mode: `MaxEncodedLen`)
	/// Storage: `Balances::Holds` (r:1 w:1)
	/// Proof: `Balances::Holds` (`max_values`: None, `max_size`: Some(229), added: 2704, mode: `MaxEncodedLen`)
	/// Storage: `PartyIdentifiers::HashIndex` (r:0 w:1)
	/// Proof: `PartyIdentifiers::HashIndex` (`max_values`: None, `max_size`: Some(56), added: 2531, mode: `MaxEncodedLen`)
	/// The range of component `x` is `[14, 1847]`.
	fn unregister(x: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `522`
		//  Estimated: `5376`
		// Minimum execution time: 71_120_000 picoseconds.
		Weight::from_parts(76_718_358, 5376)
			// Standard Error: 152
			.saturating_add(Weight::from_parts(1_232, 0).saturating_mul(x.into()))
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(3_u64))
	}
}
