# This workflow ensure the code is correctly formatted through cargo fmt as expected.
name: Check Code Formatting

on:
  workflow_dispatch:
  workflow_call:
  push:
    branches:
      - "**"
    paths:
      - "**/*.rs"
  pull_request:
    branches:
      - "*"
    paths:
      - "**/*.rs"

jobs:
  check-format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Setup Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: rustfmt

      - name: Rustfmt Check
        uses: actions-rust-lang/rustfmt@v1
